#create_clock -period 5.000 -name hdmi_clk_OBUF -waveform {0.000 2.500} [get_nets hdmi_clk_OBUF]
#set_output_delay -clock [get_clocks hdmi_clk_OBUF] -min  -2 [get_ports {hdmi_data[*]}]
#set_output_delay -clock [get_clocks hdmi_clk_OBUF] -max  0 [get_ports {hdmi_data[*]}]
#set_output_delay -clock [get_clocks hdmi_clk_OBUF] -min  -2 [get_ports hdmi_de]
#set_output_delay -clock [get_clocks hdmi_clk_OBUF] -max  0 [get_ports hdmi_de]
#set_output_delay -clock [get_clocks hdmi_clk_OBUF] -min  -2 [get_ports hdmi_hs]
#set_output_delay -clock [get_clocks hdmi_clk_OBUF] -max  0 [get_ports hdmi_hs]
#set_output_delay -clock [get_clocks hdmi_clk_OBUF] -min  -2 [get_ports hdmi_vs]
#set_output_delay -clock [get_clocks hdmi_clk_OBUF] -max  0 [get_ports hdmi_vs]

#set_property PACKAGE_PIN T16 [get_ports {hdmi_data[0]}]
#set_property PACKAGE_PIN U17 [get_ports {hdmi_data[1]}]
#set_property PACKAGE_PIN V15 [get_ports {hdmi_data[2]}]
#set_property PACKAGE_PIN W15 [get_ports {hdmi_data[3]}]
#set_property PACKAGE_PIN U18 [get_ports {hdmi_data[4]}]
#set_property PACKAGE_PIN U19 [get_ports {hdmi_data[5]}]
#set_property PACKAGE_PIN N18 [get_ports {hdmi_data[6]}]
#set_property PACKAGE_PIN P19 [get_ports {hdmi_data[7]}]
#set_property PACKAGE_PIN N20 [get_ports {hdmi_data[8]}]
#set_property PACKAGE_PIN P20 [get_ports {hdmi_data[9]}]
#set_property PACKAGE_PIN T20 [get_ports {hdmi_data[10]}]
#set_property PACKAGE_PIN U20 [get_ports {hdmi_data[11]}]
#set_property PACKAGE_PIN V20 [get_ports {hdmi_data[12]}]
#set_property PACKAGE_PIN W20 [get_ports {hdmi_data[13]}]
#set_property PACKAGE_PIN Y18 [get_ports {hdmi_data[14]}]
#set_property PACKAGE_PIN Y19 [get_ports {hdmi_data[15]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_data[0]}]

#set_property PACKAGE_PIN V16 [get_ports hdmi_vs]
#set_property PACKAGE_PIN W16 [get_ports hdmi_hs]
#set_property PACKAGE_PIN R16 [get_ports hdmi_de]
#set_property PACKAGE_PIN R17 [get_ports hdmi_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hs]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_de]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vs]

#set_property PACKAGE_PIN P15 [get_ports iic_sda_io]
#set_property PACKAGE_PIN P16 [get_ports iic_scl_io]
#set_property IOSTANDARD LVCMOS33 [get_ports iic_sda_io]
#set_property IOSTANDARD LVCMOS33 [get_ports iic_scl_io]
#set_property PULLUP true [get_ports iic_sda_io]
#set_property PULLUP true [get_ports iic_scl_io]

#set_property PACKAGE_PIN W19 [get_ports hdmi_intn]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_intn]




set_property PACKAGE_PIN T16 [get_ports {hdmi_vid_data[0]}]
set_property PACKAGE_PIN U17 [get_ports {hdmi_vid_data[1]}]
set_property PACKAGE_PIN V15 [get_ports {hdmi_vid_data[2]}]
set_property PACKAGE_PIN W15 [get_ports {hdmi_vid_data[3]}]
set_property PACKAGE_PIN U18 [get_ports {hdmi_vid_data[4]}]
set_property PACKAGE_PIN U19 [get_ports {hdmi_vid_data[5]}]
set_property PACKAGE_PIN N18 [get_ports {hdmi_vid_data[6]}]
set_property PACKAGE_PIN P19 [get_ports {hdmi_vid_data[7]}]
set_property PACKAGE_PIN N20 [get_ports {hdmi_vid_data[8]}]
set_property PACKAGE_PIN P20 [get_ports {hdmi_vid_data[9]}]
set_property PACKAGE_PIN T20 [get_ports {hdmi_vid_data[10]}]
set_property PACKAGE_PIN U20 [get_ports {hdmi_vid_data[11]}]
set_property PACKAGE_PIN V20 [get_ports {hdmi_vid_data[12]}]
set_property PACKAGE_PIN W20 [get_ports {hdmi_vid_data[13]}]
set_property PACKAGE_PIN Y18 [get_ports {hdmi_vid_data[14]}]
set_property PACKAGE_PIN Y19 [get_ports {hdmi_vid_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vid_data[15]}]
set_property PACKAGE_PIN V16 [get_ports hdmi_vid_vsync]
set_property PACKAGE_PIN W16 [get_ports hdmi_vid_hsync]
set_property PACKAGE_PIN R16 [get_ports hdmi_vid_active_video]
set_property PACKAGE_PIN R17 [get_ports hdmi_clk]
set_property PACKAGE_PIN W19 [get_ports hdmi_intn]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vid_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vid_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_intn]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vid_active_video]
set_property PACKAGE_PIN P15 [get_ports IIC_0_sda_io]
set_property PACKAGE_PIN P16 [get_ports IIC_0_scl_io]
set_property PULLUP true [get_ports IIC_0_scl_io]
set_property PULLUP true [get_ports IIC_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_sda_io]

set_property PACKAGE_PIN T11 [get_ports MB_IIC_scl_io]
set_property PACKAGE_PIN T10 [get_ports MB_IIC_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports MB_IIC_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports MB_IIC_sda_io]
set_property SLEW FAST [get_ports MB_IIC_scl_io]
set_property SLEW FAST [get_ports MB_IIC_sda_io]

set_property PACKAGE_PIN T12 [get_ports MB_SPI_io0_io]
set_property PACKAGE_PIN U12 [get_ports MB_SPI_io1_io]
set_property PACKAGE_PIN U13 [get_ports MB_SPI_sck_io]
set_property PACKAGE_PIN V13 [get_ports {MB_SPI_ss_io[1]}]
set_property PACKAGE_PIN V12 [get_ports {MB_SPI_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports MB_SPI_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports MB_SPI_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports MB_SPI_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports {MB_SPI_ss_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MB_SPI_ss_io[0]}]
set_property SLEW FAST [get_ports MB_SPI_io0_io]
set_property SLEW FAST [get_ports MB_SPI_io1_io]
set_property SLEW FAST [get_ports MB_SPI_sck_io]

set_property PACKAGE_PIN T14 [get_ports MB_UART_rxd]
set_property PACKAGE_PIN T15 [get_ports MB_UART_txd]
set_property IOSTANDARD LVCMOS33 [get_ports MB_UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports MB_UART_txd]
set_property SLEW FAST [get_ports MB_UART_txd]

